Repository ansible-collections/ibm_zos_ims, pull requests merged in 2020-05, with the labels that each got.

#13 Content/1036/add top level doc index
  docs/zos-collection-index.rst
Labels: documentation

#14 Content/update installation instructions beta2
  docs/source/index.rst
  docs/source/installation.rst
Labels: documentation

#15 Content/acbgen doc updates
  README.md
  docs/source/index.rst
  docs/source/release_notes.rst
  galaxy.yml
Labels: documentation

#11 acbgen module
  galaxy.yml
  playbook.sh
  playbooks/group_vars/all.yml
  playbooks/ims-collection-sample.yaml
  plugins/action/ims_acb_gen.py
  plugins/module_utils/ims_gen_utils.py
  plugins/modules/ims_acb_gen.py
  tests/conftest.py
  tests/functional/module_utils/ims_test_gen_utils.py
  tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py
  tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py
  tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py
  tests/helpers/ztest.py
  tests/run.sh
  tests/test_config.yml
Labels: enhancement

#17 Release v1.0.0 beta2
  README.md
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/modules/ims_acb_gen.rst
  docs/source/modules/ims_command.rst
  docs/source/modules/ims_dbd_gen.rst
  docs/source/modules/ims_psb_gen.rst
  docs/source/release_notes.rst
  docs/source/requirements.rst
  docs/templates/module.rst.j2
  docs/zos-collection-index.rst
  galaxy.yml
  playbook.sh
  playbooks/group_vars/all.yml
  playbooks/ims-collection-sample.yaml
  plugins/action/ims_acb_gen.py
  plugins/module_utils/ims_command_utils.py
  plugins/module_utils/ims_gen_utils.py
  plugins/module_utils/ims_module_error_messages.py
  plugins/modules/ims_acb_gen.py
  plugins/modules/ims_command.py
  tests/conftest.py
  tests/functional/module_utils/ims_test_gen_utils.py
  tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py
  tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py
  tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py
  tests/functional/modules/ims_command/invalid_input/test_invalid_command.py
  tests/functional/modules/ims_command/misc_commands/test_special_characters.py
  tests/helpers/ztest.py
  tests/run.sh
  tests/test_config.yml
  tests/units/modules/ims_command/test_ims_command.py
Labels: release

#18 Updated main zos-collection-index.rst with source path and removed shared content
  docs/zos-collection-index.rst
Labels: documentation
