Repository ansible-collections/ibm_zos_ims, pull requests merged in 2020-07, with the labels that each got.

#21 Content/168/add doc version support
  docs/Makefile
  docs/source/conf.py
Labels: documentation

#22 Content/168/updating docs
  docs/source/community_guides.rst
  docs/source/community_guides_docs/zos_ansible_module_testing.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/requirements.rst
  playbooks/group_vars/all.yml
  playbooks/inventory
  tests/test_config.yml
Labels: documentation

#23 Update/beta3 refs
  docs/source/release_notes.rst
  galaxy.yml
Labels: documentation

#24 Source doc updates
  docs/source/index.rst
  docs/source/modules/ims_dbd_gen.rst
  docs/source/modules/ims_psb_gen.rst
  docs/source/requirements.rst
  galaxy.yml
  tests/run.sh
Labels: documentation

#25 Feature/2464/acbgen
  plugins/action/ims_acb_gen.py
  plugins/module_utils/acbgen.py
  plugins/module_utils/ims_module_error_messages.py
  plugins/modules/ims_acb_gen.py
  tests/functional/module_utils/ims_test_gen_utils.py
  tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py
  tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py
  tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py
  tests/run.sh
  tests/test_config.yml
Labels: enhancement

#27 Dbdgen psbgen tests fixes
  playbooks/ims-collection-sample.yaml
  tests/functional/module_utils/ims_test_gen_utils.py
  tests/functional/modules/ims_dbd_gen/seq_dataset/test_invalid_input.py
  tests/functional/modules/ims_dbd_gen/uss_file/test_invalid_input.py
  tests/functional/modules/ims_dbd_gen/uss_file/test_valid_input.py
  tests/functional/modules/ims_psb_gen/uss_file/test_invalid_input.py
  tests/functional/modules/ims_psb_gen/uss_file/test_valid_input.py
  tests/test_config.yml
Labels: enhancement

#28 new acbgen source rst.
  docs/source/modules/ims_acb_gen.rst
Labels: documentation

#29 Release v1.0.0 beta3
  docs/Makefile
  docs/source/community_guides.rst
  docs/source/community_guides_docs/zos_ansible_module_testing.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/modules/ims_acb_gen.rst
  docs/source/modules/ims_dbd_gen.rst
  docs/source/modules/ims_psb_gen.rst
  docs/source/release_notes.rst
  docs/source/requirements.rst
  docs/zos-collection-index.rst
  galaxy.yml
  playbooks/group_vars/all.yml
  playbooks/ims-collection-sample.yaml
  playbooks/inventory
  plugins/action/ims_acb_gen.py
  plugins/module_utils/acbgen.py
  plugins/module_utils/dataset_utils.py
  plugins/module_utils/ims_gen_utils.py
  plugins/module_utils/ims_module_error_messages.py
  plugins/modules/ims_acb_gen.py
  plugins/modules/ims_dbd_gen.py
  plugins/modules/ims_psb_gen.py
  tests/functional/module_utils/ims_test_gen_utils.py
  tests/functional/modules/ims_acb_gen/test_ims_acb_gen_invalid_input.py
  tests/functional/modules/ims_acb_gen/test_ims_acb_gen_sample.py
  tests/functional/modules/ims_acb_gen/test_ims_acb_gen_valid_input.py
  tests/functional/modules/ims_dbd_gen/combination/test_valid_input.py
  tests/functional/modules/ims_dbd_gen/dataset/test_invalid_input.py
  tests/functional/modules/ims_dbd_gen/dataset/test_valid_input.py
  tests/functional/modules/ims_dbd_gen/seq_dataset/test_invalid_input.py
  tests/functional/modules/ims_dbd_gen/uss_file/test_invalid_input.py
  tests/functional/modules/ims_dbd_gen/uss_file/test_valid_input.py
  tests/functional/modules/ims_psb_gen/combination/test_valid_input.py
  tests/functional/modules/ims_psb_gen/dataset/test_invalid_input.py
  tests/functional/modules/ims_psb_gen/dataset/test_valid_input.py
  tests/functional/modules/ims_psb_gen/uss_file/test_invalid_input.py
  tests/functional/modules/ims_psb_gen/uss_file/test_valid_input.py
  tests/run.sh
  tests/test_config.yml
  tests/units/module_utils/test_ims_gen_utils.py
Labels: release
