Repository ansible-collections/ibm_zos_ims, pull requests merged in 2020-08, with the labels that each got.

#30 fix zoau_home undefined error. match all.yml config with core's config
  playbooks/group_vars/all.yml
Labels: bug

#32 Updated documentation model and changes
  docs/Makefile
  docs/ansible_content.rst
  docs/scripts/post-doc-gen.sh
  docs/scripts/pre-doc-gen.sh
  docs/source/community_guides.rst
  docs/source/community_guides_docs/zos_ansible_module_testing.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/license.rst
  docs/source/modules.rst
  docs/source/playbook_config_setup.rst
  docs/source/playbook_group_vars.rst
  docs/source/playbook_inventory.rst
  docs/source/playbook_run.rst
  docs/source/playbooks.rst
  docs/source/requirements.rst
  docs/source/requirements_managed.rst
  docs/zos-collection-index.rst
Labels: documentation

#33 Remove action plugins
  README.md
  docs/source/index.rst
  galaxy.yml
Labels: documentation

#34 Update cicd
  playbooks/group_vars/all.yml
  tests/test_config.yml
Labels: enhancement

#35 update references to point to 1.1.0-beta.1
  docs/source/conf.py
  galaxy.yml
Labels: enhancement

#16 DBRC Module
  playbooks/ims-collection-sample.yaml
  plugins/module_utils/IMSDbrc.py
  plugins/module_utils/ims_module_error_messages.py
  plugins/modules/ims_dbrc.py
  tests/functional/module_utils/ims_test_dbrc_utils.py
  tests/functional/module_utils/ims_test_gen_utils.py
  tests/functional/modules/ims_dbrc/commands/test_change_command.py
  tests/functional/modules/ims_dbrc/commands/test_init_change_delete_commands.py
  tests/functional/modules/ims_dbrc/commands/test_list_command.py
  tests/functional/modules/ims_dbrc/invalid_tests/test_invalid_command.py
  tests/functional/modules/ims_dbrc/invalid_tests/test_invalid_max_rc.py
  tests/functional/modules/ims_dbrc/invalid_tests/test_invalid_steplib.py
  tests/functional/modules/ims_dbrc/test_ims_dbrc_basic.py
  tests/functional/modules/ims_dbrc/test_ims_dbrc_sample.py
  tests/functional/modules/ims_dbrc/test_max_rc.py
  tests/units/modules/ims_dbrc/test_IMSDbrc.py
Labels: enhancement

#36 Release v1.1.0-beta.1
  docs/source/modules/ims_acb_gen.rst
  docs/source/modules/ims_catalog_populate.rst
  docs/source/modules/ims_catalog_purge.rst
  docs/source/modules/ims_dbrc.rst
  docs/source/release_notes.rst
  galaxy.yml
  plugins/module_utils/dbrc.py
  plugins/modules/ims_dbrc.py
  tests/units/modules/ims_dbrc/test_IMSDbrc.py
Labels: release

#37 Release v1.1.0 beta.1
  README.md
  docs/Makefile
  docs/ansible_content.rst
  docs/scripts/post-doc-gen.sh
  docs/scripts/pre-doc-gen.sh
  docs/source/community_guides.rst
  docs/source/community_guides_docs/zos_ansible_module_testing.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/license.rst
  docs/source/modules.rst
  docs/source/modules/ims_acb_gen.rst
  docs/source/modules/ims_catalog_populate.rst
  docs/source/modules/ims_catalog_purge.rst
  docs/source/modules/ims_command.rst
  docs/source/modules/ims_dbd_gen.rst
  docs/source/modules/ims_dbrc.rst
  docs/source/modules/ims_psb_gen.rst
  docs/source/playbook_config_setup.rst
  docs/source/playbook_group_vars.rst
  docs/source/playbook_inventory.rst
  docs/source/playbook_run.rst
  docs/source/playbooks.rst
  docs/source/release_notes.rst
  docs/source/requirements.rst
  docs/source/requirements_managed.rst
  docs/templates/module.rst.j2
  docs/zos-collection-index.rst
  galaxy.yml
  playbooks/group_vars/all.yml
  playbooks/ims-collection-sample.yaml
  plugins/module_utils/catalog.py
  plugins/module_utils/catalog_parser.py
  plugins/module_utils/dbrc.py
  plugins/module_utils/ims_module_error_messages.py
  plugins/modules/ims_catalog_populate.py
  plugins/modules/ims_catalog_purge.py
  plugins/modules/ims_command.py
  plugins/modules/ims_dbrc.py
  tests/ansible.cfg
  tests/functional/module_utils/ims_test_catalog_utils.py
  tests/functional/module_utils/ims_test_dbrc_utils.py
  tests/functional/module_utils/ims_test_gen_utils.py
  tests/functional/modules/ims_catalog/test_catalog.py
  tests/functional/modules/ims_catalog/test_catalog_invalid_input.py
  tests/functional/modules/ims_catalog/test_catalog_managed_acbs.py
  tests/functional/modules/ims_catalog/test_catalog_purge_analysis.py
  tests/functional/modules/ims_catalog/test_catalog_vsam.py
  tests/functional/modules/ims_dbrc/commands/test_change_command.py
  tests/functional/modules/ims_dbrc/commands/test_init_change_delete_commands.py
  tests/functional/modules/ims_dbrc/commands/test_list_command.py
  tests/functional/modules/ims_dbrc/invalid_tests/test_invalid_command.py
  tests/functional/modules/ims_dbrc/invalid_tests/test_invalid_max_rc.py
  tests/functional/modules/ims_dbrc/invalid_tests/test_invalid_steplib.py
  tests/functional/modules/ims_dbrc/test_ims_dbrc_basic.py
  tests/functional/modules/ims_dbrc/test_ims_dbrc_sample.py
  tests/functional/modules/ims_dbrc/test_max_rc.py
  tests/test_config.yml
  tests/units/modules/ims_dbrc/test_IMSDbrc.py
Labels: release

#38 fix missing space in supported shell notes.
  docs/source/requirements_managed.rst
Labels: bug, documentation

#41 Content/req managed update
  docs/source/requirements_managed.rst
Labels: bug, documentation

#43 fix test name, duplicate
  tests/functional/modules/ims_catalog/test_catalog_invalid_input.py
Labels: bug
